events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        off;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;
        root         /usr/share/nginx/html;

        location / {
            index  index.html index.htm;
            try_files $uri $uri/ =404;
        }

        # Temporary debugging path to list Nginx files in the browser
        location /debug/ {
            alias /usr/share/nginx/html/;
            autoindex on;
        }
    }
}
